import type { Metadata } from "next";
import { Header } from "@/app/(marketing)/_components/Header";
import { Footer } from "@/app/(marketing)/_components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — Tada",
  description:
    "The terms that govern your use of Tada: service description, acceptable use, content ownership, AI disclaimers, and liability.",
};

type Section = {
  heading: string;
  paragraphs: string[];
  list?: string[];
  afterList?: string[];
};

const sections: Section[] = [
  {
    heading: "1. The service",
    paragraphs: [
      "Tada is a web application that turns data files you upload — CSV, Excel, and PDF — into AI-generated dashboards, and lets you ask questions about that data in Hebrew or English. Tada is currently offered in beta: features may change, and parts of the service described as “coming soon” (including paid plans) are not yet available.",
      "By creating an account or using Tada, you agree to these terms. If you are using Tada on behalf of a business, you confirm you are authorised to accept these terms for that business.",
    ],
  },
  {
    heading: "2. Your account",
    paragraphs: [
      "You need an account to use Tada. You are responsible for keeping your login credentials secure and for all activity that happens under your account. Tell us immediately at hello@tada.app if you believe your account has been compromised.",
    ],
  },
  {
    heading: "3. Acceptable use",
    paragraphs: [
      "Use Tada for analysing data you have the right to analyse. You agree not to:",
    ],
    list: [
      "Upload data you do not have the legal right to process, including other people's personal data collected without a lawful basis.",
      "Use the service to break the law, infringe intellectual property, or harm others.",
      "Probe, scan, overload, or attempt to bypass the security or rate limits of the service.",
      "Resell, scrape, or programmatically extract the service itself (your own data and dashboards are always yours to export).",
      "Reverse engineer the service or use it to build a directly competing dataset of our prompts, rules, or outputs.",
    ],
    afterList: [
      "We may suspend accounts that violate these rules, and where practical we will warn you first.",
    ],
  },
  {
    heading: "4. Your content",
    paragraphs: [
      "You keep full ownership of everything you upload to Tada and of the dashboards generated from it. By uploading data, you grant us a limited licence to store and process that data solely to provide the service to you — generating dashboards, answering your questions, and keeping backups. This licence ends when you delete the data or your account.",
      "We do not sell your data and we do not use it to train AI models.",
    ],
  },
  {
    heading: "5. AI-generated output",
    paragraphs: [
      "Tada's dashboards, charts, and chat answers are generated by artificial intelligence. We ground generation in best-practice rules and validate output before showing it, but AI can still make mistakes: charts may be mislabelled, aggregations may be wrong, and answers may be incomplete or incorrect.",
      "Verify any number before relying on it for business, financial, tax, legal, or other significant decisions. Tada provides analysis tools, not professional advice, and you remain responsible for decisions made using the service.",
    ],
  },
  {
    heading: "6. Availability and changes",
    paragraphs: [
      "We work to keep Tada available and fast, but the service is provided “as is” and “as available”, without warranties of any kind. As a beta product, features may be added, changed, or removed. If we ever discontinue the service, we will give you reasonable notice and a way to export your data.",
    ],
  },
  {
    heading: "7. Limitation of liability",
    paragraphs: [
      "To the maximum extent permitted by law, Tada and its team are not liable for indirect, incidental, special, or consequential damages, or for loss of profits, revenue, or data, arising from your use of the service. Our total liability for any claim related to the service is limited to the amount you paid us in the twelve months before the claim arose — or, while the service is free, to ₪100.",
      "Nothing in these terms excludes liability that cannot be excluded under applicable law.",
    ],
  },
  {
    heading: "8. Termination",
    paragraphs: [
      "You can stop using Tada and delete your account at any time; deletion removes your data as described in our Privacy Policy. We may suspend or terminate accounts that breach these terms or that create risk for the service or other users. Where reasonable, we will notify you and give you a chance to export your data first.",
    ],
  },
  {
    heading: "9. Governing law",
    paragraphs: [
      "These terms are governed by the laws of the State of Israel, and any dispute arising from them or from the service will be subject to the exclusive jurisdiction of the competent courts in Israel.",
    ],
  },
  {
    heading: "10. Changes to these terms",
    paragraphs: [
      "We may update these terms from time to time. If we make material changes, we will update the date below and notify you by email or in the app before the changes take effect. Continuing to use Tada after changes take effect means you accept the updated terms.",
    ],
  },
  {
    heading: "11. Contact",
    paragraphs: [
      "Questions about these terms? Email us at hello@tada.app.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="px-4 pb-24 pt-32 sm:px-6">
        <div className="mx-auto max-w-3xl">
          <h1 className="font-display text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-muted-foreground">
            Last updated: June 2026
          </p>

          <div className="mt-10 rounded-[20px] bg-white p-8 shadow-sm sm:p-12">
            {sections.map((section, index) => (
              <section
                key={section.heading}
                className={index === 0 ? undefined : "mt-10"}
              >
                <h2 className="font-display text-xl font-semibold text-foreground">
                  {section.heading}
                </h2>
                {section.paragraphs.map((paragraph) => (
                  <p
                    key={paragraph}
                    className="mt-3 text-base leading-8 text-muted-foreground"
                  >
                    {paragraph}
                  </p>
                ))}
                {section.list && (
                  <ul className="mt-3 flex list-disc flex-col gap-2 pl-6">
                    {section.list.map((item) => (
                      <li
                        key={item}
                        className="text-base leading-8 text-muted-foreground"
                      >
                        {item}
                      </li>
                    ))}
                  </ul>
                )}
                {section.afterList?.map((paragraph) => (
                  <p
                    key={paragraph}
                    className="mt-3 text-base leading-8 text-muted-foreground"
                  >
                    {paragraph}
                  </p>
                ))}
              </section>
            ))}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
